### ISSUE TITLE
Please add a license and screen shot

### ISSUE THREAD

**Issue by unixorn** [gimbo/gimbo.zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Also, please add a license, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you pick one

**Comment by gimbo** [comment]
@unixorn Thanks for this! Just the kick I needed to add a readme, license, and screenshots, all of which I've now done. Let me know if there's anything else there you need.

**Comment by unixorn** [comment]
Adding in https://github.com/unixorn/awesome-zsh-plugins/pull/682
